
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp 
      type: mongo-db
  template:
    metadata:
      name: db-pod
      labels:
        app: myapp
        type: mongo-db
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017















# apiVersion: apps/v1
# kind: Deployment
# metadata:
#    name: db-deployment
#    labels:
#       app: myapp
#       type: database
# spec:
#    template:
#      metadata:
#        name: db-pod
#        labels:
#          app: myapp
#          type: mongo-db
#      spec:
#        containers:
#        - name: mongodb
#          image: mongo:latest
#          ports:
#          - containerPort: 27017