version: '3'
services:
    db:
      image: mysql
      volumes:
       - ./.mysql-data/db:/var/lib/mysql
      restart: always
      ports:
       - 3306: 3306
    volumes:
         /var/www/html:/var/www/html:rw
   
 
    webserver:
      depends_on: db
      image: nginx:alpine
      container_name: webserver
      restart: unless-stopped
      tty: true
      ports:
      - "80:80"
      - "443:443"
   
networks:
 - app-network
volumes:
 db_data