apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deploy
  
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: hello-page
        image: hello-world:latest  
       
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "2"


